
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bank-ocr
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort # Use NodePort to expose the frontend outside the cluster for local Kind access
